---
apiVersion: v1
kind: Secret
metadata:
  name: test-wind-wind-turbine-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/neenspa/test-wind-wind-turbine-gitops
